config/routes.rb
Rails.application.routes.draw do
  root "games#landing"
  resources :games do
    resources :bookings, only: [:create ]
  end

  resources :bookings, only: [:show, :destroy, :edit, :update, :index]

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  validates :user, presence: :true
  validates :startdate, presence: :true
  validates :enddate, presence: :true
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  validates :description, presence: true
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
  validates :status, inclusion: {in: ["in use", "returned", "available", "late" ] }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :games
  has_many :bookings

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_game, only: [:create, :new]
  before_action :set_booking, only: [:edit, :destroy, :update]

  def index
    if params[:status] == "all" || params[:status].blank?
      @bookings = current_user.bookings
    elsif params[:status] == "viewmygames"
      @bookings = Booking.joins(:game).where(games: { user_id: current_user.id })
    else
      @bookings = current_user.bookings.joins(:game).where(games: { status: params[:status]})
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @user = current_user
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.game = @game
    if @booking.save!
      redirect_to bookings_path
    else
      render 'games/show'
    end
  end

  def edit
  end

  def update
    @booking.update(status: params[:status])
    redirect_to bookings_path
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:startdate,:enddate,:status, :place)
  end

   def set_game
    @game = Game.find(params[:game_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:edit, :update, :destroy]


  def index
    @games = Game.all
  end

  def landing
     render layout: 'eventually'
  end

  def show
    @game = Game.find(params[:id])
    @user = current_user

    if Booking.exists?(user_id: current_user, game_id: @game.id)
      @booking = Booking.find_by(user_id: current_user, game_id: @game.id)
    else
      @booking = Booking.new
    end

  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.user = current_user
    if @game.save
      redirect_to game_path(@game)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @game.update(game_params)
    redirect_to game_path(@game)
  end

  def destroy
    @game.destroy
    redirect_to games_path
  end

  private

  def game_params
    params.require(:game).permit(:name, :rating, :description)
  end

  def set_game
    @game = Game.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1>Edit Game Status!</h1>
      <%= simple_form_for @booking do |f| %>

        <%= link_to booking_path(@booking, { status: "accepted"}), method: :patch do %>
          <button type="button" class="btn btn-success btn-filter">Accept</button>
        <% end %>
        <%= link_to booking_path(@booking, { status: "rejected"}), method: :patch do %>
          <button type="button" class="btn btn-danger btn-filter">Reject</button>
        <% end %>
        <button type="button" class="btn btn-info btn-filter" data-target="Contact Seller">Contact Seller</button>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<h2>Bookings</h2>

  <div class="container">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="pull-right">
          <div class="btn-group">
            <%= link_to bookings_path({ status: "viewmygames" }) do %>
              <button type="button" class="btn btn-primary btn-filter" data-target="available">View My Games</button>
            <% end %>
            <%= link_to bookings_path({ status: "available" }) do %>
              <button type="button" class="btn btn-info btn-filter" data-target="available">Available</button>
            <% end %>

            <%= link_to bookings_path({ status: "returned" }) do %>
              <button type="button" class="btn btn-success btn-filter" data-target="returned">Returned</button>
            <% end %>

            <%= link_to bookings_path({ status: "inuse" }) do %>
              <button type="button" class="btn btn-warning btn-filter" data-target="inuse">In Use</button>
            <% end %>

            <%= link_to bookings_path({ status: "late" }) do %>
              <button type="button" class="btn btn-danger btn-filter" data-target="late">Late</button>
            <% end %>

            <%= link_to bookings_path({ status: "all" }) do %>
              <button type="button" class="btn btn-default btn-filter" data-target="all">All</button>
            <% end %>

          </div>
        </div>
      </div>
    </div>
    <div class="table-container">
      <table class="table table-filter">
        <tbody>
          <% @bookings.each do |booking| %>
            <tr data-status="<%= booking.game.status%>">
<!--               <td>
                <div class="ckbox">
                  <input type="checkbox" id="checkbox1">
                  <label for="checkbox1"></label>
                </div>
              </td>
              <td>
                <a href="javascript:;" class="star">
                  <i class="glyphicon glyphicon-star"></i>
                </a>
              </td> -->
              <td>
                <div class="media">
                  <a href="#" class="pull-left">
                    <img src="https://s3.amazonaws.com/uifaces/faces/twitter/fffabs/128.jpg" class="media-photo">
                  </a>
                  <div class="media-body">
                    <h4 class="title">
                      <%= booking.game.name %>
                      <% if booking.status == "accepted" %>
                        <span class="pull-right available"><%= booking.status%></span>
                      <% else %>
                        <span class="pull-right late"><%= booking.status%></span>
                      <% end %>

                      <span class="media-meta pull-right" style="margin-right: 30px;">
                        <p>Pick up: <%= booking.startdate.strftime("%A, %b %d") %></p>
                        <p>Drop Off:<%= booking.enddate.strftime("%A, %b %d") %></p>
                      </span>


                    <h5>Rented From</h5>e
                    <p>Seller:<%= booking.game.user.email %></p>
                    <ul class="list-inline">
                      <% if booking.game.user == current_user %>
                        <li><%= link_to "Accept", booking_path(booking, { status: "accepted"}), method: :patch, class: "btn btn-success"  %></li>
                        <li><%= link_to "Reject", booking_path(booking, { status: "rejected"}), method: :patch, class: "btn btn-danger"   %></li>
                      <% end %>
                      <li><%= link_to "Show Details", game_path(booking.game),{ :class=>"btn btn-primary"} %></li>
                      <li><%# link_to "Edit", edit_booking_path(booking),{ :class=>"btn btn-primary"} %></li>
                      <li><%= link_to "Contact Game Buddy", booking_path(booking), { :class=>"btn btn-danger", method: :delete} %></li>
                    </ul>
                  </div>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/bookings/show.html.erb
<h1>Bookings #show</h1>
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h2><%= @booking.startdate %></h2>

      <h2><%= @booking.enddate %></h2>

      <h2><%= @booking.place %></h2>
      <p> <strong> User email:</strong> <%= @booking.user.email %> <strong>Game: </strong> <%= @booking.game.name %></h2>
      <p><%= link_to "Back to all bookings", bookings_path, { :class=>"btn btn-primary"}%></p>
    </div>
  </div>
</div>

app/views/games/_card.html.erb
<div class="card-container">
   <div class="game-card" data-effect="zoom">
     <button class="card__save  js-save" type="button">
       <i class="fa  fa-bookmark"></i>
     </button>
     <figure  class="card__image">
       <img src="https://c1.staticflickr.com/4/3935/32253842574_d3d449ab86_c.jpg" alt="Short description">
     </figure>
     <div class="card__header">
<!--        <figure class="card__profile">
         <img src="https://upload.wikimedia.org/wikipedia/commons/1/1c/Neil_Armstrong.jpg" alt="Short description">
       </figure> -->
     </div>
     <div class="card__body">
       <h3 class="card__name"><%= game.name %></h3>
       <p class="card__job">On Sega</p>
       <%= link_to "Show More", game_path(game), class: "card__job" %>
       <p class="card__bio"></p>
     </div>

     <!-- Cool feature for the date at the bottom left? -->

     <div class="card__footer">
       <p class="card__date">Feb 10 2018</p>
       <p class=""></p>
     </div>
  </div>
</div>

app/views/games/create.html.erb
<h1>Games#create</h1>
<p>Find me in app/views/games/create.html.erb</p>

<p> #specify <%= game.price %> <p>

app/views/games/destroy.html.erb
<h1>Games#destroy</h1>
<p>Find me in app/views/games/destroy.html.erb</p>

app/views/games/edit.html.erb
<h1>Games#edit</h1>
<p>Find me in app/views/games/new.html.erb</p>
<%= simple_form_for @game do |f| %>
        <%= f.input :name %>
        <%= f.input :rating %>
        <%= f.input :description %>
        <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/games/index.html.erb
<div class="video-container-index">
  <video id="video" autoplay muted loop src="<%= video_path "ps.mp4" %>"></video>
    <div class="container-text">
      <h1> Your Future Games </h1>
    </div>
</div>


<div class="container">
  <div class="row">
    <% @games.each do |game| %>
      <%= link_to game_path(game) do %>
        <div class="col-xs-12 col-sm-4">
          <%= render "card", game: game %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<!-- <h2>Here are your games</h2>
<%= link_to "New game", new_game_path,{ :class=>"btn btn-primary"} %>

<% @games.each do |game| %>

  <li><%= game.name %> <%= game.description %></li>
  <hr>
  <div class="card">
  <div class="card-body">
     <%= link_to "Show Details", game_path(game),{ :class=>"btn btn-primary"} %>
   <%= link_to "Edit", edit_game_path(game),{ :class=>"btn btn-primary"} %>
  <%= link_to "Delete", game_path(game), method: :delete, :class=>"btn btn-danger" %>
  </div>
</div>

  <div class="card" style="background-color: lightgray; padding: 10px;">
      <ul style="color: green"><b><%= game.name %></b></ul>
      <ul style="color: green"><%= game.description %></ul>
    <%= link_to "Show Details", game_path(game),{ :class=>"btn btn-primary"} %>
    <%= link_to "Edit", edit_game_path(game),{ :class=>"btn btn-primary"} %>
    <%= link_to "Delete", game_path(game), method: :delete, :class=>"btn btn-danger" %>
    <hr>
  </div>

<% end %>
 -->

app/views/games/landing.html.erb
<%= link_to "Sign In", new_user_registration_path, class: "btn btn-primary landin_page_btn" %>
<%= link_to "All Games", games_path, class: "btn btn-primary game_page_btn" %>

<div class="video-container">
  <video id="video" autoplay muted loop src="<%= video_path "ps.mp4" %>"></video>
</div>

<div class = "d-flex">

</div>
<header id="header">
  <h1>Welcome to Rever</h1>
  <p>Search for your game<br />
  Your next big thing. Brought to you by Rever</a>.</p>
</header>

<form id="signup-form" method="get" action="/games">
  <input type="text" name="Search" id="email" placeholder="Search Here" />
  <input type="submit" value="Search" />
</form>


<footer id="footer">
  <ul class="icons">


    <li>
      <%= link_to "GitHub.com" do %>
        <i class="fab fa-github"></i>
      <% end %>
    </li>

     <li>
      <%= link_to "twitter.com" do %>
      <i class="fab fa-twitter"></i>
      <% end %>
    </li>
     <li>
        <%= link_to "twitter.com" do %>
        <i class="fab fa-facebook-square"></i>
        <% end %>
      </li>



  </ul>
  <ul class="copyright">
    <li>&copy; Untitled.</li><li>Credits: <a href="http://html5up.net">HTML5 UP</a></li>
  </ul>
</footer>

app/views/games/new.html.erb
<div class="container", style="color: white;">
  <h1>Create new games</h1>
  <%= simple_form_for @game do |f| %>
          <%= f.input :name %>
          <%= f.input :rating %>
          <%= f.input :description %>
          <%= f.submit class: 'btn btn-primary' %>
  <% end %>

</div>

app/views/games/show.html.erb
<main class="container">
<% if @game.name == "Shadow Dancer" %>
  <div class="view hm-white-light jarallax" data-jarallax='{"speed": 0.2}' data-jarallax-video="https://www.youtube.com/watch?v=eHahEPFBSk0">
            <div class="full-bg-img">
                <div class="container flex-center">
                    <div class="row">
                        <div class="col-md-12 wow fadeIn">
                            <div class="text-center text-danger">
                                <h1 class="display-2 mb-2 wow fadeInDown" data-wow-delay="0.3s"></h1>
                                <h5 class="font-up mb-3 mt-1 font-bold wow fadeInDown" style="font-weight:bold; text-shadow: 0 0 8px #FFF, 0 -2px 12px #222, 0 -5px 15px #666;" data-wow-delay="0.4s"></h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<div class="py-2"></div>

<div>
  <%= image_tag "dancer.png", {class: "sticky-photo"}%>
</div>

<% elsif @game.name == "Super Mario" %>

  <div class="view hm-white-light jarallax" data-jarallax='{"speed": 0.2}' data-jarallax-video="https://www.youtube.com/watch?v=jeQAsUI2deY">
            <div class="full-bg-img">
                <div class="container flex-center">
                    <div class="row">
                        <div class="col-md-12 wow fadeIn">
                            <div class="text-center text-danger">
                                <h1 class="display-2 mb-2 wow fadeInDown" data-wow-delay="0.3s"></h1>
                                <h5 class="font-up mb-3 mt-1 font-bold wow fadeInDown" style="font-weight:bold; text-shadow: 0 0 8px #FFF, 0 -2px 12px #222, 0 -5px 15px #666;" data-wow-delay="0.4s"></h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<div class="py-2"></div>

<div>
  <%= image_tag "mario.jpg", {class: "sticky-photo"}%>
</div>

<% end %>
<hr>






<!-- <p> <%= link_to "See all games", games_path , { :class=>"btn btn-success btn_success"}  %>
</p> -->



<!--  Ali --

  <!-- Left Column / Headphones Image<!-- Le
  <div class="left-column">
    <%= image_tag "dancer.png", class: "left-column" %>
  </div>


<!-- Right Column -->
<div class="right-column">

<!-- Product Description -->
<div class="product-description">
  <h1 style="color:white;"><%=  @game.name %></h1>
  <p style="color: white; font-size: 20px;"><%= @game.description %></p>
</div>

<% if @booking.persisted? %>
  <h4>Status: <span class="label label-default"> <%= @booking.status %> </span></h4>
<% else %>
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Book a Game</h4>
        </div>
        <div class="modal-body">
          <div class="container">
            <div class="row" style="color: black;">
              <div class="col-xs-12 col-sm-10 col-sm-offset-1">
                <h2><%= @game.name %></h2>
                <%= simple_form_for [@game, @booking] do |f| %>
                  <h5>Start Date</h5>
                    <%= f.date_field :startdate, style: 'margin-bottom: 20px;' %>
                  <h5>End Date</h5>
                    <%= f.date_field :enddate, style: 'margin-bottom: 20px;' %>
                  <p>Seller: <%= @game.user.email %> </p>
                  <p>Location: <%= @game.user.location %> </p>

                  <p>#link to map</p>

                  <%= f.submit class: 'btn btn-success' %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <section class="content">
    <h2 style="color: white;">List of Sellers</h2>
    <div class="cards">
      <% 3.times do %>
        <div class="card">
          <div class="card__side card__side--front card__side--front-1 front-card-image">
            <div class="card__description">
              <div>
                Seller
              </div>
              <div>
                $<%= @game.price.to_i + rand(-5..5) %>
              </div>
            </div>
          </div>
          <div class="card__side card__side--back card__side--back-1">
            <div class="card__description"><svg width="24" height="24" viewBox="0 0 24 24">
              </svg></div>
              <button class="btn btn-success book-btn" type="button" class="label label-default" data-toggle="modal" data-target="#myModal">Book</button>
          </div>
        </div>
      <% end %>
    </div>
  </section>
<% end %>

<div id="overlay"></div>
  <div class="container calendar">
    <div class="header">
      <div class="icon arr prev"></div>
      <div class="month">May 2014</div>
      <div class="icon arr next"></div>
    </div>
    <table>
      <tr>
        <th>Sun</th><th>Mon</th><th>Tue</th><th>Wed</th><th>Thu</th><th>Fri</th><th>Sat</th>
      </tr>
      <tr>
        <td class="notCurMonth">29</td><td class="notCurMonth">30</td>
        <td>1</td><td>2</td><td class="curDay">3</td><td>4</td><td>5</td>
      </tr>
      <tr>
        <td>6</td><td class="holiday">7</td><td>8</td><td>9</td><td>10</td><td>11</td><td>12</td>
      </tr>
      <tr>
        <td>13</td><td>14</td><td>15</td><td>16</td><td>17</td><td>18</td><td>19</td>
      </tr>
      <tr>
        <td>20</td><td>21</td><td>22</td><td class="holiday">23</td><td>24</td><td>25</td><td>26</td>
      </tr>
      <tr>
        <td>27</td><td>28</td><td>29</td><td>30</td>
        <td class="notCurMonth">1</td><td class="notCurMonth">2</td class="notCurMonth"><td class="notCurMonth">3</td>
      </tr>
    </table>
    <button class="button-big" id="add_event">Add event</button>
  </div>


 <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="js/popper.min.js"></script>
    <script src="https://mdbootstrap.com/previews/docs/latest/js/bootstrap.min.js"></script>
    <script src="https://mdbootstrap.com/previews/docs/latest/js/mdb.min.js"></script>
    <script src="https://mdbootstrap.com/previews/docs/latest/js/jarallax.js"></script>
    <script src="https://mdbootstrap.com/previews/docs/latest/js/jarallax-video.js"></script>
    <script>
        new WOW().init();
    </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!--
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
-->
    <title>Rever-bnb</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>

    <%= render 'shared/navbar2' %>

    <%= yield %>
    <%# render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>


  </body>
</html>

app/views/layouts/eventually.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>REVER</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
     <%= stylesheet_link_tag 'eventually', media: 'all' %>
  </head>
  <body>
    <video autoplay muted loop id="myVideo">
      <source src="rain.mp4" type="video/mp4">
    </video>
    <%= yield %>
    <%= javascript_include_tag 'application' %>

  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small color">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2018 Copyright:
    <a href="https://mdbootstrap.com/bootstrap-tutorial/"> Rever.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/shared/_navbar2.html.erb
<!--
<nav  -->class="navbar navbar-expand-lg navbar-dark default-color-dark fixed-top" style="position: relative">
  <%= link_to root_path do %>
      <%= image_tag "logo.jpg", class: "logo"%>
  <% end %>
  <%= link_to "Sign In", new_user_session_path, class: "landing_page_btn" %>
  <%= link_to "All Games", games_path, class: "gam_page_btn" %>

<!-- </nav> -->